clean up command run, add tests

diff --git a/mash b/mash
--- a/mash
+++ b/mash
@@ -49,13 +49,13 @@ run:whatever:seconds(){
 # dump just the header
 run:mash:header () {
   set +x #output based
-  grep -B100 -e '{make\.sh user}' mash || (printf "ERROR" >/dev/stderr; exit 1)
+  grep -B150 -e '{make\.sh user}' mash || (printf "ERROR" >/dev/stderr; exit 1)
 }
 
 # dump just the footer
 run:mash:footer () {
   set +x # output based
-  grep -A100 -e '{make\.sh common}' mash || (printf "ERROR" >dev/stderr; exit 1)
+  grep -A150 -e '{make\.sh common}' mash || (printf "ERROR" >dev/stderr; exit 1)
 }
 
 run:mash:dump(){
@@ -65,6 +65,17 @@ run:mash:dump(){
 }
 run:dump(){
   run:mash:dump
+}
+
+run:test(){
+  run:dump | grep '#!/usr/bin/env bash'
+  run:dump | tail -n 2 | grep 'run:'
+  run:test:args 1 2 3 | grep "1 2 3"
+  echo "completed tests succesfully"
+}
+
+run:test:args(){
+  echo "$@"
 }
 
 
@@ -81,7 +92,6 @@ run:help(){
   exit 1
 }
 [ -z "${1:-}" ] && run:help
-cmd="$1"
-shift
-[[ "$cmd" == completion:* ]] || set -x
-run:"$cmd" "$@"
+[ "${1:11}" == "completion:" ] || set -x
+run:"$1" "${@:2}"
+
